Enforce c+11 on OSX
Recommendation of StackOverflow - https://stackoverflow.com/questions/45047508/error-unknown-type-name-constexpr-during-make-in-mac-os-x

This will allow the snappy include to be detected, otherwise it will fail due to:

... eleveldb/c_src/system/include/snappy.h:199:10: error: unknown type name 'constexpr'
  static constexpr int kBlockLog = 16;

Also required in COMMON_FLAGS so that leveldb will compile with snappy